<?php

namespace MidasSoft\DominicanBankParser;

class Deposit
{
    /**
     * The amount of the deposit.
     *
     * @var float
     */
    private $amount;

    /**
     * The date of the deposit.
     *
     * @var string
     */
    private $date;

    /**
     * The description of the deposit.
     *
     * @var string
     */
    private $description;

    /**
     * The term of the deposit.
     *
     * @var string
     */
    private $term;

    /**
     * The Unique Id the deposit.
     *
     * @var string
     */
    private $unique_id = null;

    /**
     * Creates a new Deposit object.
     *
     * @param float  $amount
     * @param string $date
     * @param string $description
     * @param string $term
     * @param null   $unique_id
     */
    public function __construct($amount, $date, $description, $term, $unique_id = null)
    {
        $this->amount = $amount;
        $this->date = $date;
        $this->description = $description;
        $this->term = $term;
        $this->unique_id = $unique_id;
    }

    /**
     * Returns the amount property.
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Returns the date property.
     *
     * @return string
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Returns the description property.
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Returns the term property.
     *
     * @return string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * Returns the unique id generated by the logic of each bank.
     *
     * @return string
     */
    public function getUniqueId(): string
    {
        return $this->unique_id ?? '';
    }

    /**
     * Returns a string representation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return sprintf('%s|%s|%s|%s|%s', $this->amount, $this->date, $this->description, $this->term, $this->unique_id);
    }
}
